use sqlx::FromRow;

#[derive(Debug, FromRow)]
pub struct Card {
    pub id: i32,
    pub card_id: String,
    pub object: String,
    pub name: String,
    pub color_indicator: Option<u8>,
    pub produced_mana: Option<u8>,
    pub loyalty: Option<i32>,
    pub artist: Option<String>,
    pub oracle_id: Option<String>,
    pub type_line: Option<String>,
    pub lang: Option<String>,
    pub content_warning: bool,
    pub converted_mana_cost: f32,
    pub image_status: Option<String>,
    pub flavor_text: Option<String>,
    pub arena_id: Option<i32>,
    pub illustration_id: Option<String>,
    pub oracle_text: Option<String>,
    pub colors: Option<u8>,
    pub color_identity: Option<u8>,
    pub rarity: Option<String>,
    pub power: Option<i32>,
    pub toughness: Option<i32>,
    pub set_name: Option<String>,
    pub set_id: Option<String>,
    pub set_type: Option<String>,
    pub set_short: Option<String>,
    pub penny_rank: Option<String>,
    pub variation: bool,
    pub mtgo_id: Option<i32>,
    pub booster: bool,
    pub border_color: Option<String>,
    pub foil: bool,
    pub game_changer: bool,
    pub reprint: bool,
    pub layout: Option<String>,
    pub reserved: bool,
    pub digital: bool,
    pub mana_cost: Option<String>,
    pub mtgo: bool,
    pub arena: bool,
    pub paper: bool,
    pub promo: bool,
}
