[package]
name = "ponder"
version = "0.1.0"
edition = "2024"

[dependencies]
color-eyre = "0.6.4"
crossterm = "0.29.0"
ratatui = "0.29.0"
tokio = { version = "1.45.0", features = ["full"] }
ponder-db = { path = "../ponder-db" }
dotstore = "0.1.0"
anyhow = "1.0.98"
async-trait = "0.1.88"
