create table if not exists card (
    id text not null primary key,
    object text not null,
    name text not null,
    color_indicator text,
    produced_mana text,
    loyalty integer,
    artist text,
    oracle_id text,
    lang text,
    content_warning boolean,
    converted_mana_cost real,
    image_status text,
    flavor_text text,
    arena_id integer,
    illustration_id text,
    oracle_text text,
    color_identity text,
    rarity text,
    card_type text,
    subtype text,
    legendary boolean,
    power integer,
    toughness integer,
    set_name text,
    set_id text,
    set_type text,
    set_short text,
    penny_rank text,
    variation boolean,
    mtgo_id integer,
    colors text,
    booster boolean,
    border_color text,
    foil boolean,
    game_changer boolean,
    reprint boolean,
    layout text,
    reserved boolean,
    digital boolean,
    keywords text,
    mana_cost text,
    mtgo boolean,
    arena boolean,
    paper boolean,
    promo boolean
);

create table if not exists images (
    card_id text not null,
    large text,
    small text,
    art_crop text,
    normal text,
    border_crop text,
    foreign key (card_id) references card(id)
);

create table if not exists legalities (
    card_id text not null,
    standard boolean,
    pioneer boolean,
    modern boolean,
    premodern boolean,
    legacy boolean,
    vintage boolean,
    commander boolean,
    pauper boolean,
    paupercommander boolean,
    penny boolean,
    historic boolean,
    predh boolean,
    future boolean,
    alchemy boolean,
    oathbreaker boolean,
    timeless boolean,
    gladiator boolean,
    standardbrawl boolean,
    duel boolean,
    oldschool boolean,
    explorer boolean,
    brawl boolean,
    foreign key (card_id) references card(id)
);

create index if not exists idx_card on card(id);
